import { Element } from '../types';

export interface DayPillarArchetype {
  index: number;           // 0-59 in the sexagenary cycle
  stemIndex: number;       // 0-9
  branchIndex: number;     // 0-11
  hanja: string;           // e.g. "甲子"
  korean: string;          // e.g. "갑자"
  name: string;            // Archetype name in English
  imagery: string;         // Evocative image/metaphor
  coreIdentity: string;    // Core personality description
  elementDynamic: string;  // How stem and branch interact
  lifeTheme: string;       // Central life theme
}

// All 60 pillars of the sexagenary cycle with archetype data
export const SIXTY_PILLARS: DayPillarArchetype[] = [
  // 甲 (Yang Wood) series
  { index: 0,  stemIndex: 0, branchIndex: 0,  hanja: '甲子', korean: '갑자', name: 'The Pioneer at Sea', imagery: 'A great tree growing on the ocean shore, roots reaching deep into hidden waters', coreIdentity: 'Visionary leader with profound hidden depth. Outwardly strong and ambitious, inwardly intuitive and emotionally complex.', elementDynamic: 'Yang Wood over Yang Water. Water nourishes Wood, giving tremendous growth potential. The tree drinks from an endless well.', lifeTheme: 'Channeling boundless inner resources into bold external achievement' },
  { index: 1,  stemIndex: 0, branchIndex: 1,  hanja: '甲丑', korean: '갑축', name: 'The Tree on Frozen Earth', imagery: 'A tall tree standing alone in winter farmland, patient and enduring', coreIdentity: 'Patient builder who grows slowly but unshakably. Values substance over flash. Stubborn loyalty defines relationships.', elementDynamic: 'Yang Wood over Yin Earth. Wood controls Earth, but Earth here is cold and resistant. Growth requires sustained effort.', lifeTheme: 'Building lasting legacies through persistent effort and quiet determination' },
  { index: 2,  stemIndex: 0, branchIndex: 2,  hanja: '甲寅', korean: '갑인', name: 'The Tiger in the Forest', imagery: 'A towering tree rooted in its native forest, powerful and commanding', coreIdentity: 'Natural-born leader radiating confidence. When stem and branch share the same element, identity is unified and powerful.', elementDynamic: 'Yang Wood over Yang Wood. Complete alignment. Double Wood creates immense vitality but risks inflexibility.', lifeTheme: 'Leading with authenticity and learning the art of yielding' },
  { index: 3,  stemIndex: 0, branchIndex: 3,  hanja: '甲卯', korean: '갑묘', name: 'The Towering Bamboo', imagery: 'A mighty tree in a lush garden, surrounded by flowering vines', coreIdentity: 'Magnetic presence with artistic sensibility. Strong core identity softened by aesthetic awareness and social grace.', elementDynamic: 'Yang Wood over Yin Wood. Same element, different polarity. The great tree shelters smaller growth beneath.', lifeTheme: 'Balancing personal strength with gentleness and nurturing others' },
  { index: 4,  stemIndex: 0, branchIndex: 4,  hanja: '甲辰', korean: '갑진', name: 'The Dragon Rider', imagery: 'A tree growing through dragon bones in misty marshland, mystical and transformative', coreIdentity: 'Charismatic transformer who bridges worlds. Practical ambition fused with visionary imagination.', elementDynamic: 'Yang Wood over Yang Earth. Wood penetrates and reshapes Earth. Hidden Water in 辰 nourishes secretly.', lifeTheme: 'Transforming dreams into reality through disciplined imagination' },
  { index: 5,  stemIndex: 0, branchIndex: 5,  hanja: '甲巳', korean: '갑사', name: 'The Phoenix Tree', imagery: 'A tree catching fire at dawn, burning beautifully, always regenerating', coreIdentity: 'Creative force who channels intense energy outward. Brilliant but prone to burning fast. Must learn pacing.', elementDynamic: 'Yang Wood feeds Yin Fire. Wood exhausts itself producing Fire. Beautiful output but draining process.', lifeTheme: 'Sustaining creative brilliance without self-destruction' },
  { index: 6,  stemIndex: 0, branchIndex: 6,  hanja: '甲午', korean: '갑오', name: 'The Sun-Warped Oak', imagery: 'A great oak standing in blazing noon sun, casting dramatic shadows', coreIdentity: 'Bold performer with a flair for the dramatic. Generous and warm but can overwhelm others with intensity.', elementDynamic: 'Yang Wood feeds Yang Fire. Maximum output energy. Wood is consumed by Fire, creating spectacular but unsustainable display.', lifeTheme: 'Learning to shine without burning out, finding sustainable expression' },
  { index: 7,  stemIndex: 0, branchIndex: 7,  hanja: '甲未', korean: '갑미', name: 'The Orchard Keeper', imagery: 'A fruit tree in a summer garden, productive and nurturing', coreIdentity: 'Naturally generous soul who finds purpose in providing for others. Practical idealist with strong family orientation.', elementDynamic: 'Yang Wood controls Yin Earth. Wood shapes dry Earth into something productive. Hidden Fire and Wood create warmth.', lifeTheme: 'Finding fulfillment through nurturing others and building community' },
  { index: 8,  stemIndex: 0, branchIndex: 8,  hanja: '甲申', korean: '갑신', name: 'The Carved Warrior', imagery: 'A tree being shaped by a master sculptor, painful but beautiful', coreIdentity: 'Resilient soul forged through challenge. Metal carves Wood into something refined. Growth comes through adversity.', elementDynamic: 'Yang Wood is controlled by Yang Metal. The tree is cut and shaped. Painful but transformative.', lifeTheme: "Embracing life's challenges as the sculptor of character" },
  { index: 9,  stemIndex: 0, branchIndex: 9,  hanja: '甲酉', korean: '갑유', name: 'The Pruned Bonsai', imagery: 'A carefully shaped bonsai, constrained but exquisite', coreIdentity: 'Refined through limitation. External pressures create inner beauty. Learns discipline through constraint.', elementDynamic: 'Yang Wood controlled by Yin Metal. Precise cuts shape the tree. Pressure creates artistry.', lifeTheme: 'Finding freedom and beauty within structure and limitation' },
  { index: 10, stemIndex: 0, branchIndex: 10, hanja: '甲戌', korean: '갑술', name: 'The Autumn Sentinel', imagery: 'A tree on an autumn hilltop, leaves falling, standing guard over the harvest', coreIdentity: 'Wise protector with a sense of duty. Understands cycles of growth and loss. Natural guardian and counselor.', elementDynamic: 'Yang Wood over Yang Earth (with hidden Metal and Fire). Complex terrain. The tree faces multiple forces.', lifeTheme: 'Standing firm through all seasons with wisdom and grace' },
  { index: 11, stemIndex: 0, branchIndex: 11, hanja: '甲亥', korean: '갑해', name: 'The Rainforest Giant', imagery: 'A massive tree in endless rain, growing without limit in tropical abundance', coreIdentity: 'Boundlessly energetic and expansive. Water feeds Wood endlessly. Enormous potential but must choose focus.', elementDynamic: 'Yang Wood over Yin Water. Water generates Wood abundantly. Hidden Wood amplifies growth further.', lifeTheme: 'Directing infinite potential into meaningful channels' },

  // 乙 (Yin Wood) series
  { index: 12, stemIndex: 1, branchIndex: 0,  hanja: '乙丑', korean: '을축', name: 'The Winter Vine', imagery: 'A delicate vine wrapped around frozen earth, surviving through flexibility', coreIdentity: 'Adaptable survivor who bends but never breaks. Finds strength in softness and persistence in adversity.', elementDynamic: 'Yin Wood over Yin Earth. Gentle control. The vine slowly covers and transforms the soil.', lifeTheme: 'Transforming harsh environments through gentle persistence' },
  { index: 13, stemIndex: 1, branchIndex: 1,  hanja: '乙卯', korean: '을묘', name: 'The Secret Garden', imagery: 'A hidden garden in full bloom, private and self-contained', coreIdentity: 'Deeply authentic and self-contained. Rich inner world. Blooms most beautifully when given privacy and freedom.', elementDynamic: 'Yin Wood over Yin Wood. Complete alignment in Yin polarity. Gentle but deeply rooted.', lifeTheme: 'Cultivating authentic beauty from within, regardless of external approval' },
  { index: 14, stemIndex: 1, branchIndex: 2,  hanja: '乙巳', korean: '을사', name: 'The Flowering Torch', imagery: 'Flowers blooming around a candle flame, beauty emerging from warmth', coreIdentity: 'Artistic soul drawn to expression and beauty. Uses gentle creativity to illuminate the world. Warm and inviting.', elementDynamic: 'Yin Wood feeds Yin Fire. Gentle output. The flower offers its beauty willingly.', lifeTheme: 'Sharing inner beauty with the world through creative expression' },
  { index: 15, stemIndex: 1, branchIndex: 3,  hanja: '乙未', korean: '을미', name: 'The Summer Meadow', imagery: 'Wildflowers swaying in a warm summer field, free and abundant', coreIdentity: 'Free spirit with natural warmth. Effortlessly attracts others. Values freedom and beauty above material gain.', elementDynamic: 'Yin Wood controls Yin Earth. Gentle mastery. Flowers transform barren ground into beauty.', lifeTheme: 'Creating beauty and abundance wherever life plants you' },
  { index: 16, stemIndex: 1, branchIndex: 4,  hanja: '乙酉', korean: '을유', name: 'The Jeweled Flower', imagery: 'A delicate orchid encrusted with frost crystals, fragile beauty under pressure', coreIdentity: 'Beauty forged under pressure. External refinement masks inner tension. Seeks perfection in everything.', elementDynamic: 'Yin Wood controlled by Yin Metal. The flower is cut by frost. Beauty and pain intertwined.', lifeTheme: 'Finding strength in vulnerability and beauty in imperfection' },
  { index: 17, stemIndex: 1, branchIndex: 5,  hanja: '乙亥', korean: '을해', name: 'The Water Lily', imagery: 'A lotus floating on deep still water, serene and deeply nourished', coreIdentity: 'Deeply intuitive and spiritually nourished. Calm exterior hides profound emotional depth. Natural healer.', elementDynamic: 'Yin Wood over Yin Water. Water generates Wood gently. The lotus rises from the depths.', lifeTheme: "Rising above life's murky waters to bloom in serene beauty" },

  // 丙 (Yang Fire) series
  { index: 18, stemIndex: 2, branchIndex: 0,  hanja: '丙子', korean: '병자', name: 'The Midnight Sun', imagery: 'The sun shining at midnight over arctic waters, impossible yet real', coreIdentity: 'Walking paradox. Warm and radiant yet drawn to depth and mystery. Illuminates hidden places others fear to explore.', elementDynamic: 'Yang Fire over Yang Water. Fire and Water oppose. Dynamic tension creates steam, power, transformation.', lifeTheme: 'Reconciling opposites and finding power in paradox' },
  { index: 19, stemIndex: 2, branchIndex: 2,  hanja: '丙寅', korean: '병인', name: 'The Sunrise Tiger', imagery: 'The rising sun blazing through a forest canopy, setting the trees ablaze with golden light', coreIdentity: 'Unstoppable force of nature. Warmth, ambition, and natural authority combined. Born to lead and inspire.', elementDynamic: 'Yang Fire over Yang Wood. Wood feeds Fire perfectly. Endless fuel for the blaze.', lifeTheme: 'Channeling abundant energy into inspirational leadership' },
  { index: 20, stemIndex: 2, branchIndex: 4,  hanja: '丙辰', korean: '병진', name: "The Dragon's Flame", imagery: 'A dragon breathing fire across misty mountains, transformative and awe-inspiring', coreIdentity: 'Transformative visionary who changes everything they touch. Grand ambitions matched by genuine capability.', elementDynamic: 'Yang Fire over Yang Earth. Fire produces Earth. The flame creates new ground wherever it burns.', lifeTheme: 'Creating lasting transformation through passionate vision' },
  { index: 21, stemIndex: 2, branchIndex: 6,  hanja: '丙午', korean: '병오', name: 'The High Noon Sun', imagery: 'The sun at its absolute zenith, blazing with maximum intensity', coreIdentity: 'Maximum Fire energy. Brilliant, charismatic, impossible to ignore. Must learn that intensity needs rest.', elementDynamic: 'Yang Fire over Yang Fire. Double Fire. Peak intensity. Nothing hidden, everything illuminated.', lifeTheme: 'Learning that true power includes knowing when to dim the light' },
  { index: 22, stemIndex: 2, branchIndex: 8,  hanja: '丙申', korean: '병신', name: 'The Forge Master', imagery: 'A blazing forge shaping raw metal into sacred weapons', coreIdentity: 'Disciplined transformer who shapes raw material into refined purpose. Combines passion with precision.', elementDynamic: 'Yang Fire controls Yang Metal. The flame masters the metal. Creative destruction for a higher purpose.', lifeTheme: 'Forging discipline from passion and purpose from raw talent' },
  { index: 23, stemIndex: 2, branchIndex: 10, hanja: '丙戌', korean: '병술', name: 'The Harvest Bonfire', imagery: 'A great bonfire burning on an autumn hilltop, celebrating the harvest', coreIdentity: 'Warm-hearted gatherer who creates community through shared warmth. Generous, celebratory, slightly nostalgic.', elementDynamic: 'Yang Fire produces Yang Earth. Fire creates more Earth. Building community and legacy.', lifeTheme: 'Building lasting warmth and community through generous spirit' },

  // 丁 (Yin Fire) series
  { index: 24, stemIndex: 3, branchIndex: 1,  hanja: '丁丑', korean: '정축', name: 'The Candlelight Scribe', imagery: 'A single candle burning in a cold study, illuminating ancient texts', coreIdentity: 'Focused intellectual with spiritual depth. Finds truth in quiet contemplation. Knowledge is power.', elementDynamic: 'Yin Fire over Yin Earth. Gentle warmth meets cold earth. The candle stubbornly fights the darkness.', lifeTheme: 'Illuminating truth through focused study and quiet perseverance' },
  { index: 25, stemIndex: 3, branchIndex: 3,  hanja: '丁卯', korean: '정묘', name: 'The Lantern in the Garden', imagery: 'A paper lantern hanging in a moonlit garden, casting soft warm light', coreIdentity: 'Gentle illuminator who creates beauty and warmth in intimate spaces. Romantic, artistic, quietly powerful.', elementDynamic: 'Yin Fire over Yin Wood. Wood feeds Fire gently. The garden fuels the lantern effortlessly.', lifeTheme: 'Creating intimate beauty and nurturing close connections' },
  { index: 26, stemIndex: 3, branchIndex: 5,  hanja: '丁巳', korean: '정사', name: 'The Sacred Flame', imagery: 'An eternal flame burning in an ancient temple, never extinguished', coreIdentity: 'Intensely focused and spiritually powerful. Small flame with enormous transformative potential. Magnetic and mysterious.', elementDynamic: 'Yin Fire over Yin Fire (hidden). Fire intensified. Concentrated power in a small vessel.', lifeTheme: 'Channeling inner fire into spiritual or creative mastery' },
  { index: 27, stemIndex: 3, branchIndex: 7,  hanja: '丁未', korean: '정미', name: 'The Summer Hearth', imagery: 'A warm hearth glowing in a countryside kitchen, nourishing all who gather', coreIdentity: 'Nurturing warmth personified. Creates home wherever they go. Emotional intelligence is their superpower.', elementDynamic: 'Yin Fire produces Yin Earth. Gentle creation. Warmth builds nurturing ground.', lifeTheme: 'Nourishing others through emotional warmth and steady presence' },
  { index: 28, stemIndex: 3, branchIndex: 9,  hanja: '丁酉', korean: '정유', name: "The Jeweler's Torch", imagery: "A precise flame under a jeweler's loupe, revealing hidden facets of precious gems", coreIdentity: 'Precise observer who sees beauty others miss. Perfectionist with artistic vision. Refines everything they touch.', elementDynamic: 'Yin Fire controls Yin Metal. Precise heat shapes precious metal. Artistry through controlled intensity.', lifeTheme: 'Revealing hidden beauty through meticulous attention and refined craft' },
  { index: 29, stemIndex: 3, branchIndex: 11, hanja: '丁亥', korean: '정해', name: 'The Lighthouse', imagery: 'A lighthouse beam cutting through fog and rain on a stormy night', coreIdentity: 'Guiding light in dark times. Resilient hope that shines brightest when others struggle. Natural counselor.', elementDynamic: 'Yin Fire over Yin Water. Fire and Water tension. The light persists despite the storm.', lifeTheme: "Being a beacon of hope and guidance through life's storms" },

  // 戊 (Yang Earth) series
  { index: 30, stemIndex: 4, branchIndex: 0,  hanja: '戊子', korean: '무자', name: 'The Mountain Spring', imagery: 'A great mountain with a hidden spring flowing from its heart', coreIdentity: 'Solid and reliable with hidden emotional depth. Appears immovable but harbors flowing inner currents.', elementDynamic: 'Yang Earth over Yang Water. Earth contains Water. The mountain holds the spring within.', lifeTheme: 'Balancing steadfast stability with hidden emotional wisdom' },
  { index: 31, stemIndex: 4, branchIndex: 2,  hanja: '戊寅', korean: '무인', name: 'The Forested Mountain', imagery: 'A grand mountain covered in ancient forest, teeming with life', coreIdentity: 'Powerful foundation that supports growth in all directions. Natural protector and provider. Commanding presence.', elementDynamic: 'Yang Earth with Yang Wood on top. Wood grows on Earth. The mountain nurtures the forest.', lifeTheme: 'Providing stable ground for others to grow and flourish' },
  { index: 32, stemIndex: 4, branchIndex: 4,  hanja: '戊辰', korean: '무진', name: 'The Dragon Mountain', imagery: 'A sacred mountain shrouded in mist, where dragons are said to dwell', coreIdentity: 'Majestic and mysterious. Double Earth creates immense stability and authority. Natural commander with spiritual depth.', elementDynamic: 'Yang Earth over Yang Earth. Maximum stability and authority. Immovable, for better and worse.', lifeTheme: 'Wielding natural authority with wisdom and spiritual awareness' },
  { index: 33, stemIndex: 4, branchIndex: 6,  hanja: '戊午', korean: '무오', name: 'The Volcanic Peak', imagery: 'A volcano radiating heat from its summit, powerful and magnetic', coreIdentity: 'Charismatic authority fueled by passionate inner fire. Warm, generous, impossible to ignore. Born leader.', elementDynamic: 'Yang Earth over Yang Fire. Fire produces Earth. Internal fire strengthens the mountain from within.', lifeTheme: 'Channeling inner passion into commanding, warm leadership' },
  { index: 34, stemIndex: 4, branchIndex: 8,  hanja: '戊申', korean: '무신', name: 'The Mountain of Treasure', imagery: 'A mountain rich with precious metals and gems hidden in its veins', coreIdentity: 'Abundant potential waiting to be excavated. Practical genius. Creates value from seemingly ordinary situations.', elementDynamic: 'Yang Earth produces Yang Metal. The mountain yields its treasures. Productive and generous.', lifeTheme: 'Discovering and sharing the treasures within oneself and the world' },
  { index: 35, stemIndex: 4, branchIndex: 10, hanja: '戊戌', korean: '무술', name: 'The Desert Fortress', imagery: 'An ancient stone fortress standing alone in vast desert, unbreakable', coreIdentity: 'Ultimate endurance and self-reliance. Nothing breaks this spirit. Can be isolated but never conquered.', elementDynamic: 'Yang Earth over Yang Earth (with hidden Metal and Fire). Triple Earth energy. Maximum rigidity.', lifeTheme: 'Finding the balance between impenetrable strength and openness to change' },

  // 己 (Yin Earth) series
  { index: 36, stemIndex: 5, branchIndex: 1,  hanja: '己丑', korean: '기축', name: 'The Fertile Valley', imagery: 'A quiet valley of rich farmland, ready for planting, patient and yielding', coreIdentity: 'Receptive nurturer who creates abundance through patience. Humble exterior masks deep inner wealth.', elementDynamic: 'Yin Earth over Yin Earth. Gentle receptivity doubled. Fertile, patient, quietly powerful.', lifeTheme: 'Creating abundance through patience, humility, and receptive wisdom' },
  { index: 37, stemIndex: 5, branchIndex: 3,  hanja: '己卯', korean: '기묘', name: 'The Tended Garden', imagery: 'Rich garden soil shaped by careful hands, producing beautiful flowers', coreIdentity: 'Patient cultivator who brings out the best in others. Controlled by Wood but creates beauty from it.', elementDynamic: 'Yin Earth controlled by Yin Wood. Wood shapes Earth. The gardener shapes the soil with love.', lifeTheme: 'Allowing life to shape you while retaining the power to nurture beauty' },
  { index: 38, stemIndex: 5, branchIndex: 5,  hanja: '己巳', korean: '기사', name: 'The Kiln Master', imagery: 'Clay being fired in a kiln, transformed from soft earth into enduring art', coreIdentity: 'Transformative creator who uses heat and pressure to create lasting beauty. Alchemist of human experience.', elementDynamic: 'Yin Earth over Yin Fire. Fire strengthens Earth. The kiln hardens soft clay into something permanent.', lifeTheme: 'Transforming raw experience into lasting wisdom and beauty' },
  { index: 39, stemIndex: 5, branchIndex: 7,  hanja: '己未', korean: '기미', name: 'The Summer Soil', imagery: 'Warm, dry earth in midsummer, absorbing heat and holding seeds for autumn', coreIdentity: 'Deep patience and inner warmth. Absorbs everything, holds secrets, and nurtures growth at the right time.', elementDynamic: 'Yin Earth over Yin Earth. Same energy. Complete self-knowledge. Centered and self-contained.', lifeTheme: 'Trusting divine timing and nurturing hidden seeds of potential' },
  { index: 40, stemIndex: 5, branchIndex: 9,  hanja: '己酉', korean: '기유', name: "The Potter's Earth", imagery: "Soft clay on a potter's wheel, yielding to skilled hands, becoming exquisite", coreIdentity: 'Refined beauty through willingness to be shaped. Elegant, perceptive, values quality over quantity.', elementDynamic: 'Yin Earth produces Yin Metal. Earth yields precious metal. Soft nurture creates hard beauty.', lifeTheme: "Yielding gracefully to life's shaping forces while maintaining inner beauty" },
  { index: 41, stemIndex: 5, branchIndex: 11, hanja: '己亥', korean: '기해', name: 'The River Delta', imagery: 'Rich alluvial soil where a great river meets the sea, endlessly fertile', coreIdentity: 'Where stability meets flow. Adaptable nurturer who thrives at crossroads and transitions. Bridge between worlds.', elementDynamic: 'Yin Earth over Yin Water. Earth contains Water. The delta is shaped by water but holds its ground.', lifeTheme: 'Thriving at the intersection of stability and change' },

  // 庚 (Yang Metal) series
  { index: 42, stemIndex: 6, branchIndex: 0,  hanja: '庚子', korean: '경자', name: 'The Sword in the Lake', imagery: 'A legendary sword resting at the bottom of a still, deep lake', coreIdentity: 'Hidden power beneath calm surface. Sharp mind with emotional depth. Reveals true strength only when needed.', elementDynamic: 'Yang Metal over Yang Water. Metal produces Water. The sword rests in the water it creates.', lifeTheme: 'Concealing true power until the moment it is truly needed' },
  { index: 43, stemIndex: 6, branchIndex: 2,  hanja: '庚寅', korean: '경인', name: 'The Axe in the Forest', imagery: 'A sharp axe embedded in a tree stump, tool of both destruction and creation', coreIdentity: 'Direct action meets living resistance. Cutting through obstacles is natural but must learn what to preserve.', elementDynamic: 'Yang Metal controls Yang Wood. The axe cuts the tree. Power through decisive action.', lifeTheme: 'Learning discernment in the use of natural cutting power' },
  { index: 44, stemIndex: 6, branchIndex: 4,  hanja: '庚辰', korean: '경진', name: 'The Mountain Sword', imagery: 'A great sword forged from mountain ore, still connected to the earth', coreIdentity: 'Raw power being refined into purpose. Tremendous potential that needs direction and discipline to fulfill.', elementDynamic: 'Yang Metal in Yang Earth. Earth produces Metal. The ore becomes the blade. Potential becoming power.', lifeTheme: 'Refining raw potential into purposeful, directed power' },
  { index: 45, stemIndex: 6, branchIndex: 6,  hanja: '庚午', korean: '경오', name: 'The Blade in the Fire', imagery: 'A sword being tempered in flames, gaining strength through heat', coreIdentity: 'Power refined through passion and trials. Fire controls Metal, creating something stronger than before.', elementDynamic: 'Yang Metal controlled by Yang Fire. The blade is tempered by fire. Stronger for having endured.', lifeTheme: "Growing stronger through life's trials and passionate challenges" },
  { index: 46, stemIndex: 6, branchIndex: 8,  hanja: '庚申', korean: '경신', name: 'The Pure Blade', imagery: 'A perfectly forged sword, gleaming and sharp, ready for action', coreIdentity: 'Pure Metal energy. Decisive, sharp, direct. Says what they mean and does what they say. Natural warrior.', elementDynamic: 'Yang Metal over Yang Metal. Maximum sharpness and clarity. Nothing hidden, nothing wasted.', lifeTheme: 'Wielding clarity and decisiveness with honor and purpose' },
  { index: 47, stemIndex: 6, branchIndex: 10, hanja: '庚戌', korean: '경술', name: "The Guardian's Sword", imagery: 'An ancestral sword hanging above the family hearth, protector of the lineage', coreIdentity: 'Fierce protector of what matters most. Loyal to the bone. Fights for family, honor, and tradition.', elementDynamic: 'Yang Metal in Yang Earth. Earth supports Metal. The mountain holds the sword. Grounded power.', lifeTheme: 'Protecting what is sacred with unwavering loyalty and strength' },

  // 辛 (Yin Metal) series
  { index: 48, stemIndex: 7, branchIndex: 1,  hanja: '辛丑', korean: '신축', name: 'The Buried Gem', imagery: 'A precious gemstone still encased in rough stone, waiting to be discovered', coreIdentity: 'Hidden value beneath unassuming exterior. Patient refinement reveals extraordinary beauty. Late bloomer.', elementDynamic: 'Yin Metal in Yin Earth. Earth holds Metal. The gem waits in the earth for the right moment.', lifeTheme: 'Patiently revealing inner brilliance when the time is right' },
  { index: 49, stemIndex: 7, branchIndex: 3,  hanja: '辛卯', korean: '신묘', name: 'The Silver Scissors', imagery: 'Delicate silver scissors cutting silk, precise and purposeful', coreIdentity: 'Elegant precision in all things. Cuts away what is unnecessary with grace. Aesthetic perfectionist.', elementDynamic: 'Yin Metal controls Yin Wood. Precise cutting. The scissors shape the fabric with artistry.', lifeTheme: 'Refining life through precise choices and elegant discernment' },
  { index: 50, stemIndex: 7, branchIndex: 5,  hanja: '辛巳', korean: '신사', name: "The Alchemist's Gold", imagery: "Raw metal being transmuted in an alchemist's crucible, becoming gold", coreIdentity: 'Transformative intelligence that turns base experience into wisdom. Strategic, mysterious, quietly powerful.', elementDynamic: 'Yin Metal controlled by Yin Fire. Fire refines Metal. Pressure creates purity and value.', lifeTheme: "Transmuting life's challenges into golden wisdom and refined purpose" },
  { index: 51, stemIndex: 7, branchIndex: 7,  hanja: '辛未', korean: '신미', name: 'The Desert Rose', imagery: 'A crystal formation growing in desert sand, mineral beauty in harsh conditions', coreIdentity: 'Beauty born from harsh conditions. Finds elegance in simplicity. Values quality over quantity.', elementDynamic: 'Yin Metal in Yin Earth. Earth nurtures Metal gently. The crystal grows slowly in dry earth.', lifeTheme: 'Creating beauty and value even in the most challenging environments' },
  { index: 52, stemIndex: 7, branchIndex: 9,  hanja: '辛酉', korean: '신유', name: 'The Perfect Diamond', imagery: 'A flawless diamond catching light from every angle, brilliant and hard', coreIdentity: 'Pure Yin Metal. Brilliantly perceptive, impossibly high standards, both beautiful and cutting.', elementDynamic: 'Yin Metal over Yin Metal. Maximum refinement. Pure crystalline clarity. Nothing impure survives.', lifeTheme: 'Embracing imperfection as the ultimate refinement of perfectionism' },
  { index: 53, stemIndex: 7, branchIndex: 11, hanja: '辛亥', korean: '신해', name: 'The Pearl Diver', imagery: 'A pearl growing secretly in deep ocean waters, luminous and precious', coreIdentity: 'Hidden treasure nourished by deep waters. Emotional intelligence paired with sharp perception. Quietly magnetic.', elementDynamic: 'Yin Metal produces Yin Water. Metal creates Water. The pearl is born from the depths.', lifeTheme: "Diving deep into life's waters to retrieve hidden pearls of wisdom" },

  // 壬 (Yang Water) series
  { index: 54, stemIndex: 8, branchIndex: 0,  hanja: '壬子', korean: '임자', name: 'The Great Ocean', imagery: 'The vast open ocean under a full moon, endless depth and power', coreIdentity: 'Boundless depth and power. Maximum Water energy. Intuitive, strategic, emotionally vast. Can be overwhelming.', elementDynamic: "Yang Water over Yang Water. Doubled ocean. Infinite depth. Danger of drowning in one's own depths.", lifeTheme: 'Channeling oceanic inner power without being lost in its depths' },
  { index: 55, stemIndex: 8, branchIndex: 2,  hanja: '壬寅', korean: '임인', name: 'The Monsoon River', imagery: 'A mighty river swollen with monsoon rains, rushing through ancient forests', coreIdentity: 'Powerful forward momentum meets living growth. Strategic intelligence that adapts and nourishes everything in its path.', elementDynamic: 'Yang Water generates Yang Wood. Water feeds the forest. Power creates growth wherever it flows.', lifeTheme: 'Using strategic power to nourish growth in self and others' },
  { index: 56, stemIndex: 8, branchIndex: 4,  hanja: '壬辰', korean: '임진', name: "The Dragon's Sea", imagery: 'A storm-tossed sea with a dragon rising from the depths, magnificent chaos', coreIdentity: 'Magnificent chaos that creates new worlds. Visionary strategist who thrives in turbulence. Born for transformation.', elementDynamic: 'Yang Water over Yang Earth. Water is contained by Earth, but hidden Water in 辰 adds depth.', lifeTheme: 'Rising from chaos to create magnificent new realities' },
  { index: 57, stemIndex: 8, branchIndex: 6,  hanja: '壬午', korean: '임오', name: 'The Steam Engine', imagery: 'Water meeting fire to create steam, pure kinetic energy and power', coreIdentity: 'Dynamic tension between emotion and passion creates tremendous drive. Unstoppable when focused.', elementDynamic: 'Yang Water over Yang Fire. Water and Fire clash. The collision creates steam and power.', lifeTheme: 'Harnessing internal contradictions as a source of extraordinary power' },
  { index: 58, stemIndex: 8, branchIndex: 8,  hanja: '壬申', korean: '임신', name: 'The Waterfall', imagery: 'A great waterfall cascading down a metal cliff, thunderous and awe-inspiring', coreIdentity: 'Powerful flow meeting solid structure. Impressive presence that commands attention. Strategic thinker with dramatic flair.', elementDynamic: 'Yang Water produced by Yang Metal. Metal creates Water. The cliff gives birth to the waterfall.', lifeTheme: 'Turning structural support into dramatic, powerful expression' },
  { index: 59, stemIndex: 8, branchIndex: 10, hanja: '壬戌', korean: '임술', name: 'The Autumn Lake', imagery: 'A deep lake surrounded by autumn mountains, still on the surface, deep below', coreIdentity: 'Still waters running deep. Outward calm conceals strategic depth. Patient, observant, strikes at the perfect moment.', elementDynamic: 'Yang Water contained by Yang Earth. The lake is held by the mountains. Controlled power.', lifeTheme: 'Mastering the art of strategic patience and perfect timing' },

  // 癸 (Yin Water) series
  { index: 12, stemIndex: 9, branchIndex: 1,  hanja: '癸丑', korean: '계축', name: 'The Underground Spring', imagery: 'A hidden spring flowing beneath frozen winter earth, unseen but vital', coreIdentity: 'Hidden nurturer whose influence flows unseen. Quiet power that sustains others without seeking credit.', elementDynamic: 'Yin Water in Yin Earth. Water is contained. The spring flows underground, vital but invisible.', lifeTheme: 'Sustaining life through hidden, selfless contribution' },
  { index: 25, stemIndex: 9, branchIndex: 3,  hanja: '癸卯', korean: '계묘', name: 'The Morning Dew', imagery: 'Dewdrops glistening on fresh spring leaves at dawn, pure and life-giving', coreIdentity: 'Pure nurturing energy. Gentle, life-giving, quietly essential. Small actions create enormous growth.', elementDynamic: 'Yin Water generates Yin Wood. Dew feeds the leaves. Small gifts create great beauty.', lifeTheme: 'Nurturing extraordinary growth through gentle, consistent care' },
  { index: 38, stemIndex: 9, branchIndex: 5,  hanja: '癸巳', korean: '계사', name: 'The Mist Walker', imagery: 'Ethereal mist swirling around a sacred flame, mysterious and ever-changing', coreIdentity: 'Enigmatic soul walking between worlds. Intuitive, spiritual, hard to pin down. Transforms like mist.', elementDynamic: 'Yin Water clashes with Yin Fire. Mist meets flame. Neither conquers the other. Eternal dance.', lifeTheme: 'Embracing mystery and finding power in being unknowable' },
  { index: 51, stemIndex: 9, branchIndex: 7,  hanja: '癸未', korean: '계미', name: 'The Summer Rain', imagery: 'Gentle rain falling on parched summer earth, bringing relief and renewal', coreIdentity: 'Gentle healer who arrives when most needed. Emotional intelligence combined with nurturing practicality.', elementDynamic: 'Yin Water over Yin Earth. Water nourishes Earth. Rain falls gently on dry ground.', lifeTheme: 'Being the gentle relief that renews and heals when the world is parched' },
  { index: 4,  stemIndex: 9, branchIndex: 9,  hanja: '癸酉', korean: '계유', name: 'The Crystal Stream', imagery: 'A clear stream flowing over polished river stones, pure and sparkling', coreIdentity: 'Crystal clarity of perception. Sees through deception instantly. Sharp mind in a gentle package.', elementDynamic: 'Yin Water produced by Yin Metal. Metal creates clear water. The stones polish the stream.', lifeTheme: 'Achieving clarity of purpose through refined perception and honest self-reflection' },
  { index: 17, stemIndex: 9, branchIndex: 11, hanja: '癸亥', korean: '계해', name: 'The Deep Well', imagery: 'An ancient well reaching down to the water table, an inexhaustible source', coreIdentity: 'Infinite emotional and spiritual depth. The deepest Yin Water. Psychic, empathic, profoundly intuitive.', elementDynamic: 'Yin Water over Yin Water. Maximum Yin Water. Unfathomable depth. The well never runs dry.', lifeTheme: 'Drawing from infinite inner wells of wisdom, intuition, and compassion' },
];

// Build lookup map by stemIndex*12+branchIndex for fast retrieval
const PILLAR_LOOKUP = new Map<number, DayPillarArchetype>();
for (const pillar of SIXTY_PILLARS) {
  PILLAR_LOOKUP.set(pillar.stemIndex * 12 + pillar.branchIndex, pillar);
}

export function getDayPillarArchetype(stemIndex: number, branchIndex: number): DayPillarArchetype | undefined {
  return PILLAR_LOOKUP.get(stemIndex * 12 + branchIndex);
}
