import { getTenGod, resolveAllTenGods } from '../analysis/ten-gods-resolver';
import { STEMS } from '../constants/stems';
import { BRANCHES } from '../constants/branches';
import { TenGod, Element, YinYang, FourPillars } from '../types';

// Helper to get stem by index
const S = (i: number) => STEMS[i];

describe('getTenGod', () => {
  // Full 10x10 matrix test
  // Day Master: 甲 (Yang Wood, index 0)
  describe('Day Master: 甲 (Yang Wood)', () => {
    const dm = S(0); // 甲 Yang Wood

    test('甲 vs 甲 = Companion (same element, same polarity)', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.Companion);
    });
    test('甲 vs 乙 = Rob Wealth (same element, diff polarity)', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.RobWealth);
    });
    test('甲 vs 丙 = Eating God (generates, same polarity)', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.EatingGod);
    });
    test('甲 vs 丁 = Hurting Officer (generates, diff polarity)', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.HurtingOfficer);
    });
    test('甲 vs 戊 = Indirect Wealth (controls, same polarity)', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.IndirectWealth);
    });
    test('甲 vs 己 = Direct Wealth (controls, diff polarity)', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.DirectWealth);
    });
    test('甲 vs 庚 = Seven Killings (controlled by, same polarity)', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.SevenKillings);
    });
    test('甲 vs 辛 = Direct Officer (controlled by, diff polarity)', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.DirectOfficer);
    });
    test('甲 vs 壬 = Indirect Seal (generated by, same polarity)', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.IndirectSeal);
    });
    test('甲 vs 癸 = Direct Seal (generated by, diff polarity)', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.DirectSeal);
    });
  });

  // Day Master: 乙 (Yin Wood, index 1)
  describe('Day Master: 乙 (Yin Wood)', () => {
    const dm = S(1); // 乙 Yin Wood

    test('乙 vs 甲 = Rob Wealth', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.RobWealth);
    });
    test('乙 vs 乙 = Companion', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.Companion);
    });
    test('乙 vs 丙 = Hurting Officer', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.HurtingOfficer);
    });
    test('乙 vs 丁 = Eating God', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.EatingGod);
    });
    test('乙 vs 戊 = Direct Wealth', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.DirectWealth);
    });
    test('乙 vs 己 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.IndirectWealth);
    });
    test('乙 vs 庚 = Direct Officer', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.DirectOfficer);
    });
    test('乙 vs 辛 = Seven Killings', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.SevenKillings);
    });
    test('乙 vs 壬 = Direct Seal', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.DirectSeal);
    });
    test('乙 vs 癸 = Indirect Seal', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.IndirectSeal);
    });
  });

  // Day Master: 丙 (Yang Fire, index 2)
  describe('Day Master: 丙 (Yang Fire)', () => {
    const dm = S(2); // 丙 Yang Fire

    test('丙 vs 甲 = Indirect Seal (generated by, same polarity)', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.IndirectSeal);
    });
    test('丙 vs 乙 = Direct Seal (generated by, diff polarity)', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.DirectSeal);
    });
    test('丙 vs 丙 = Companion', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.Companion);
    });
    test('丙 vs 丁 = Rob Wealth', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.RobWealth);
    });
    test('丙 vs 戊 = Eating God', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.EatingGod);
    });
    test('丙 vs 己 = Hurting Officer', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.HurtingOfficer);
    });
    test('丙 vs 庚 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.IndirectWealth);
    });
    test('丙 vs 辛 = Direct Wealth', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.DirectWealth);
    });
    test('丙 vs 壬 = Seven Killings', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.SevenKillings);
    });
    test('丙 vs 癸 = Direct Officer', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.DirectOfficer);
    });
  });

  // Day Master: 丁 (Yin Fire, index 3)
  describe('Day Master: 丁 (Yin Fire)', () => {
    const dm = S(3);

    test('丁 vs 甲 = Direct Seal', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.DirectSeal);
    });
    test('丁 vs 乙 = Indirect Seal', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.IndirectSeal);
    });
    test('丁 vs 丙 = Rob Wealth', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.RobWealth);
    });
    test('丁 vs 丁 = Companion', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.Companion);
    });
    test('丁 vs 戊 = Hurting Officer', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.HurtingOfficer);
    });
    test('丁 vs 己 = Eating God', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.EatingGod);
    });
    test('丁 vs 庚 = Direct Wealth', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.DirectWealth);
    });
    test('丁 vs 辛 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.IndirectWealth);
    });
    test('丁 vs 壬 = Direct Officer', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.DirectOfficer);
    });
    test('丁 vs 癸 = Seven Killings', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.SevenKillings);
    });
  });

  // Day Master: 戊 (Yang Earth, index 4)
  describe('Day Master: 戊 (Yang Earth)', () => {
    const dm = S(4);

    test('戊 vs 甲 = Seven Killings (controlled by, same polarity)', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.SevenKillings);
    });
    test('戊 vs 乙 = Direct Officer (controlled by, diff polarity)', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.DirectOfficer);
    });
    test('戊 vs 丙 = Indirect Seal (generated by, same polarity)', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.IndirectSeal);
    });
    test('戊 vs 丁 = Direct Seal (generated by, diff polarity)', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.DirectSeal);
    });
    test('戊 vs 戊 = Companion', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.Companion);
    });
    test('戊 vs 己 = Rob Wealth', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.RobWealth);
    });
    test('戊 vs 庚 = Eating God', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.EatingGod);
    });
    test('戊 vs 辛 = Hurting Officer', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.HurtingOfficer);
    });
    test('戊 vs 壬 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.IndirectWealth);
    });
    test('戊 vs 癸 = Direct Wealth', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.DirectWealth);
    });
  });

  // Day Master: 己 (Yin Earth, index 5)
  describe('Day Master: 己 (Yin Earth)', () => {
    const dm = S(5);

    test('己 vs 甲 = Direct Officer', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.DirectOfficer);
    });
    test('己 vs 乙 = Seven Killings', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.SevenKillings);
    });
    test('己 vs 丙 = Direct Seal', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.DirectSeal);
    });
    test('己 vs 丁 = Indirect Seal', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.IndirectSeal);
    });
    test('己 vs 戊 = Rob Wealth', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.RobWealth);
    });
    test('己 vs 己 = Companion', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.Companion);
    });
    test('己 vs 庚 = Hurting Officer', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.HurtingOfficer);
    });
    test('己 vs 辛 = Eating God', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.EatingGod);
    });
    test('己 vs 壬 = Direct Wealth', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.DirectWealth);
    });
    test('己 vs 癸 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.IndirectWealth);
    });
  });

  // Day Master: 庚 (Yang Metal, index 6)
  describe('Day Master: 庚 (Yang Metal)', () => {
    const dm = S(6);

    test('庚 vs 甲 = Indirect Wealth (controls, same polarity)', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.IndirectWealth);
    });
    test('庚 vs 乙 = Direct Wealth (controls, diff polarity)', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.DirectWealth);
    });
    test('庚 vs 丙 = Seven Killings (controlled by, same polarity)', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.SevenKillings);
    });
    test('庚 vs 丁 = Direct Officer (controlled by, diff polarity)', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.DirectOfficer);
    });
    test('庚 vs 戊 = Indirect Seal (generated by, same polarity)', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.IndirectSeal);
    });
    test('庚 vs 己 = Direct Seal (generated by, diff polarity)', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.DirectSeal);
    });
    test('庚 vs 庚 = Companion', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.Companion);
    });
    test('庚 vs 辛 = Rob Wealth', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.RobWealth);
    });
    test('庚 vs 壬 = Eating God', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.EatingGod);
    });
    test('庚 vs 癸 = Hurting Officer', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.HurtingOfficer);
    });
  });

  // Day Master: 辛 (Yin Metal, index 7)
  describe('Day Master: 辛 (Yin Metal)', () => {
    const dm = S(7);

    test('辛 vs 甲 = Direct Wealth', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.DirectWealth);
    });
    test('辛 vs 乙 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.IndirectWealth);
    });
    test('辛 vs 丙 = Direct Officer', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.DirectOfficer);
    });
    test('辛 vs 丁 = Seven Killings', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.SevenKillings);
    });
    test('辛 vs 戊 = Direct Seal', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.DirectSeal);
    });
    test('辛 vs 己 = Indirect Seal', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.IndirectSeal);
    });
    test('辛 vs 庚 = Rob Wealth', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.RobWealth);
    });
    test('辛 vs 辛 = Companion', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.Companion);
    });
    test('辛 vs 壬 = Hurting Officer', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.HurtingOfficer);
    });
    test('辛 vs 癸 = Eating God', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.EatingGod);
    });
  });

  // Day Master: 壬 (Yang Water, index 8)
  describe('Day Master: 壬 (Yang Water)', () => {
    const dm = S(8);

    test('壬 vs 甲 = Eating God (generates, same polarity)', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.EatingGod);
    });
    test('壬 vs 乙 = Hurting Officer (generates, diff polarity)', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.HurtingOfficer);
    });
    test('壬 vs 丙 = Indirect Wealth (controls, same polarity)', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.IndirectWealth);
    });
    test('壬 vs 丁 = Direct Wealth (controls, diff polarity)', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.DirectWealth);
    });
    test('壬 vs 戊 = Seven Killings (controlled by, same polarity)', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.SevenKillings);
    });
    test('壬 vs 己 = Direct Officer (controlled by, diff polarity)', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.DirectOfficer);
    });
    test('壬 vs 庚 = Indirect Seal (generated by, same polarity)', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.IndirectSeal);
    });
    test('壬 vs 辛 = Direct Seal (generated by, diff polarity)', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.DirectSeal);
    });
    test('壬 vs 壬 = Companion', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.Companion);
    });
    test('壬 vs 癸 = Rob Wealth', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.RobWealth);
    });
  });

  // Day Master: 癸 (Yin Water, index 9)
  describe('Day Master: 癸 (Yin Water)', () => {
    const dm = S(9);

    test('癸 vs 甲 = Hurting Officer', () => {
      expect(getTenGod(dm, S(0))).toBe(TenGod.HurtingOfficer);
    });
    test('癸 vs 乙 = Eating God', () => {
      expect(getTenGod(dm, S(1))).toBe(TenGod.EatingGod);
    });
    test('癸 vs 丙 = Direct Wealth', () => {
      expect(getTenGod(dm, S(2))).toBe(TenGod.DirectWealth);
    });
    test('癸 vs 丁 = Indirect Wealth', () => {
      expect(getTenGod(dm, S(3))).toBe(TenGod.IndirectWealth);
    });
    test('癸 vs 戊 = Direct Officer', () => {
      expect(getTenGod(dm, S(4))).toBe(TenGod.DirectOfficer);
    });
    test('癸 vs 己 = Seven Killings', () => {
      expect(getTenGod(dm, S(5))).toBe(TenGod.SevenKillings);
    });
    test('癸 vs 庚 = Direct Seal', () => {
      expect(getTenGod(dm, S(6))).toBe(TenGod.DirectSeal);
    });
    test('癸 vs 辛 = Indirect Seal', () => {
      expect(getTenGod(dm, S(7))).toBe(TenGod.IndirectSeal);
    });
    test('癸 vs 壬 = Rob Wealth', () => {
      expect(getTenGod(dm, S(8))).toBe(TenGod.RobWealth);
    });
    test('癸 vs 癸 = Companion', () => {
      expect(getTenGod(dm, S(9))).toBe(TenGod.Companion);
    });
  });

  // Verify symmetry properties
  describe('Symmetry properties', () => {
    test('Same element, same polarity always yields Companion', () => {
      for (const stem of STEMS) {
        expect(getTenGod(stem, stem)).toBe(TenGod.Companion);
      }
    });

    test('Same element, opposite polarity always yields Rob Wealth', () => {
      for (let i = 0; i < 10; i += 2) {
        expect(getTenGod(S(i), S(i + 1))).toBe(TenGod.RobWealth);
        expect(getTenGod(S(i + 1), S(i))).toBe(TenGod.RobWealth);
      }
    });
  });
});

describe('resolveAllTenGods', () => {
  test('resolves ten gods for a complete four pillars chart', () => {
    // Example: 甲子 year, 丙寅 month, 戊辰 day, 庚申 hour
    const fourPillars: FourPillars = {
      year:  { stem: S(0), branch: BRANCHES[0] },  // 甲子
      month: { stem: S(2), branch: BRANCHES[2] },  // 丙寅
      day:   { stem: S(4), branch: BRANCHES[4] },  // 戊辰
      hour:  { stem: S(6), branch: BRANCHES[8] },  // 庚申
    };

    const dayMaster = fourPillars.day.stem; // 戊 (Yang Earth)
    const result = resolveAllTenGods(fourPillars, dayMaster);

    // Year stem: 甲 vs 戊 = Seven Killings (Wood controls Earth? No: Earth is controlled BY Wood)
    // Wood controls Earth -> from 戊's perspective, 甲 controls 戊 -> controlled_by, same polarity -> Seven Killings
    expect(result['year_stem']).toBe(TenGod.SevenKillings);

    // Month stem: 丙 vs 戊 = Indirect Seal (Fire generates Earth, same polarity)
    expect(result['month_stem']).toBe(TenGod.IndirectSeal);

    // Hour stem: 庚 vs 戊 = Eating God (Earth generates Metal, same polarity)
    expect(result['hour_stem']).toBe(TenGod.EatingGod);

    // Hidden stems should be resolved
    // 子 hidden: 癸 -> vs 戊 = Direct Wealth (Earth controls Water, diff polarity)
    expect(result['year_hidden_0']).toBe(TenGod.DirectWealth);
  });

  test('handles chart without hour pillar', () => {
    const fourPillars: FourPillars = {
      year:  { stem: S(0), branch: BRANCHES[0] },
      month: { stem: S(2), branch: BRANCHES[2] },
      day:   { stem: S(4), branch: BRANCHES[4] },
      hour:  null,
    };

    const dayMaster = fourPillars.day.stem;
    const result = resolveAllTenGods(fourPillars, dayMaster);

    expect(result['hour_stem']).toBeUndefined();
    expect(result['year_stem']).toBeDefined();
    expect(result['month_stem']).toBeDefined();
  });
});
